# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-21 17:14
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('hitcount', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hit',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2016, 11, 21, 17, 14, 56, 436873, tzinfo=utc)),
        ),
    ]
