# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-22 13:21
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('hitcount', '0002_auto_20161121_1714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hit',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2016, 11, 22, 13, 21, 45, 859462, tzinfo=utc)),
        ),
    ]
